### ISSUE TITLE
Minimal theme

### ISSUE THREAD

**Issue by TfTHacker** [nothingislost/obsidian-query-control#1]
Cool little plugin :-)

If using minimal theme, the icons buttons are aligned wrong. Seems to work ok with other themes.

**Comment by TfTHacker** [comment]
Haha… got first issue even before released to the crazy obsidian community :-)

**Comment by nothingislost** [comment]
Haha, nice. I use Minimal and I'm not seeing the issue. Can you show me a screenshot?

![image](https://user-images.githubusercontent.com/89109712/154198222-1364dc5e-6d4a-4ed8-83a0-98981764e844.png)

**Comment by TfTHacker** [comment]
You know what, now that you said that I found a css snippet causing this issue. Its a snippet to hide the title of the embedded search. So this i can fix. 

Sorry about that, jumped the gun. But I did get the prestigious honor of first repo issue. So it was worth it.

**Comment by nothingislost** [comment]
No worries, it's a good point. Hiding that text is probably fairly common. If you don't mind, post the snippet you end up using to fix it and I'll see if I can incorporate it conditionally somehow
