### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by fieldrabbit21** [nothingislost/obsidian-query-control#12]
In the instruction for manual installation it syas:
"Copy over main.js, manifest.json to your vault VaultFolder/.obsidian/plugins/obsidian-embedded-query-control/."

I cannot find file main.js?

**Comment by nothingislost** [comment]
I'd recommend installing using BRAT but if you'd like to manual install, the files are in the releases section https://github.com/nothingislost/obsidian-query-control/releases/tag/0.4.0
