### ISSUE TITLE
It seems that query-control's render function does not work in obsidian 0.15.0

### ISSUE THREAD

**Issue by zhao414** [nothingislost/obsidian-query-control#13]
the query progress bar keeps running, and the render button cannot be clicked.

**Comment by erikwestra** [comment]
Yes, I have the same problem.

**Comment by jackli89** [comment]
I have the same issue. Any workarounds for the time being? I rely pretty heavily on this plugin.

**Comment by nothingislost** [comment]
Please try out https://github.com/nothingislost/obsidian-query-control/releases/tag/0.4.0 and let me know how it works out for you all

**Comment by abhayprasanna** [comment]
Works great for me now!

**Comment by zhao414** [comment]
Works great for me, too!

**Comment by zhao414** [comment]
https://github.com/nothingislost/obsidian-query-control/releases/tag/0.4.0 solved the issue!
