### ISSUE TITLE
Breaks search

### ISSUE THREAD

**Issue by colintedford** [nothingislost/obsidian-query-control#17]
Query Control seems to break search in the latest Obsidian. When use the search in the left side pane, it finds a few results and continues searching without finding the rest of the results. Disabling and re-enabling Query Control fixes the problem until the app is restarted. 

I'm seeing this in Obsidian Mobile 1.3.0 (63) on iOS 15.5 and 0.15.6 (installer 0.14.2; I haven't updated that yet) on MacOS Monterey 12.3.

The connection to Query Control and the workaround were [discovered by Obsidian Forum user Flexit](https://forum.obsidian.md/t/search-feature-is-not-working/40584/4).

**Comment by nothingislost** [comment]
I can't replicate this and this is over a year old (my fault, not yours). Feel free to reopen if this is still an issue.
