### ISSUE TITLE
`path:` doesn't work

### ISSUE THREAD

**Issue by stoweboyd** [nothingislost/obsidian-query-control#18]
I am trying to limit search to a specific file, and then to find a string, but I never get any results.

`path:"2022 journal/2022-07-23.md"`
`line:("- [?]")`

The path attribute is taken from the default search.

**Comment by nothingislost** [comment]
Works for me. I think the issue is probably with the `line:("- [?]")` portion of this query. Feel free to reopen if it's still a problem.
