### ISSUE TITLE
Request to add license

### ISSUE THREAD

**Issue by branchm** [nothingislost/obsidian-query-control#20]
Hi - Awesome plugin!!!  But I can't can't use it at work unless there is a clear license, preferably MIT, GPL (not AGPL), or Apache - I'm no expert on licensing, but this is what I understand from some of my company's documentation.  Anyway, would you consider adding a LICENSE?  Thanks!

**Comment by branchm** [comment]
Any update on this?

**Comment by nothingislost** [comment]
License added
