### ISSUE TITLE
embedded query generates extreme long pages in exported PDF

### ISSUE THREAD

**Issue by zhao414** [nothingislost/obsidian-query-control#27]
to reproduce:

in Note 1:
---start of note 1----

aaaaaa ^aipjmk

- search
	- ![[Note1#^aipjmk]]

\`\`\`query
content:(search)
\`\`\`

-------- end of note 1----
and export the the pdf

the embedded query result turned into a infinite long page in the exported PDF

![image](https://user-images.githubusercontent.com/15528506/218796417-47756771-ed4a-42af-96f9-8096786e6c5f.png)

system info
SYSTEM INFO:
	Obsidian version: v1.1.13
	Installer version: v1.1.9
	Operating system: Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 22.2.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 35
	Plugins enabled: 1
		1: Query Control v0.5.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by nothingislost** [comment]
I can't seem to replicate this but let me know if this still happens in the latest 0.6.0 release

**Comment by zhao414** [comment]
This is no longer an issue. Thank you for your time!
