### ISSUE TITLE
[feature request] add `hide control bar` and `disable highlight` option

### ISSUE THREAD

**Issue by makerjackie** [nothingislost/obsidian-query-control#5]
sometimes I don't want to show `control bar` and also highlight, I want a simple, clean query result

thx for your wonderful job!!!

**Comment by mlevison** [comment]
+1. Assuming the original author is referring to:
![Dashboard_-_MarkPKM_-_Obsidian_v0_15_3](https://user-images.githubusercontent.com/140902/177206424-820b1e96-3847-4207-8789-6eba45a50a6b.jpg)

**Comment by mretier** [comment]
You could use a CSS snippet to hide it. 
The following snippet worked for me:

```
.nav-header {
    display: none;
}
```
