### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by Pedro-Cataneo** [nothingislost/obsidian-query-control#51]
![image](https://github.com/user-attachments/assets/590d5f32-53ab-466d-85fc-aacb65f298be)

I couldn't get it working back no matter what i do.

**Comment by piogab** [comment]
I have the same problem. Have you found a solution @Pedro-Cataneo ?

**Comment by Pedro-Cataneo** [comment]
Nothing. Stopped using for now, unfortunately.

**Comment by asderad** [comment]
Same here, happened recently for no immediately apparent reason. 
Would love a fix or at least a workaround as this has become surprisingly important to my workflow.

**Comment by piogab** [comment]
Suddenly after restarting Obsidian today it somehow started working for me. I don't know why. I haven't changed anything. Yesterday I was restarting multiple times and it didn't help 🤷.

**Comment by asderad** [comment]
@piogab It is rather inconsistent which makes troubleshooting a hassle. 

Restarting Obsidian did work once for me and then never again.

Reinstalling the plugin did resolve the issue for me once until restarting Obsidian; after which reinstalling did nothing anymore. 

And the plugin seems to work fine in another vault which is identical to the first one (regarding plugins) so I can't pinpoint the issue. 


I've installed better-search-views which fulfills a similar role whilst awaiting some kind of solution I rather not hope for.

**Comment by ReaderGuy42** [comment]
Through trial and error I figured out that in my case I have to leave the Core Plugin `Backlinks` on, otherwise the plugin doesn't work. Does this work for you?

**Comment by Pedro-Cataneo** [comment]
> Through trial and error I figured out that in my case I have to leave the Core Plugin `Backlinks` on, otherwise the plugin doesn't work. Does this work for you?

Man that was exactly it! I had disabled all the core plugins that i dont use and didnt realised that was the reason query control wasnt working. Thanks, man

**Comment by Pedro-Cataneo** [comment]
Through trial and error I figured out that in my case I have to leave the Core Plugin Backlinks on, otherwise the plugin doesn't work. Does this work for you?

Man that was exactly it! I had disabled all the core plugins that i dont use and didnt realised that was the reason query control wasnt working. Thanks, man

**Comment by ReaderGuy42** [comment]
Cool :)
